### PR TITLE
Add Gradle 8 support

### PR DESCRIPTION
**Pull request by tattuu**
This is a pull request that addresses the error occurring in this pull request (https://github.com/gdelataillade/alarm/pull/130).

I also included an upgrade of the Gradle version that was missed last time. 

Additionally, there are modifications made within the 'example' directory.

### CODE REVIEW

**Comment by gdelataillade** [comment]
Hi @tattuu 

That's awesome thank you so much !

I want to test your PR but I'm having a lot of trouble updating Java (11 -> 17).

I have installed Java 17 but it still says:
`Android Gradle plugin requires Java 17 to run. You are currently using Java 11.`

When I do `./gradlew --version` I have:

```
------------------------------------------------------------
Gradle 8.5
------------------------------------------------------------

Build time:   2023-11-29 14:08:57 UTC
Revision:     28aca86a7180baa17117e0e5ba01d8ea9feca598

Kotlin:       1.9.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.10 (Amazon.com Inc. 17.0.10+7-LTS)
OS:           Mac OS X 14.2.1 aarch64
```

When I do `java --version` I have:
```
openjdk 17.0.10 2024-01-16 LTS
OpenJDK Runtime Environment Corretto-17.0.10.7.1 (build 17.0.10+7-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.10.7.1 (build 17.0.10+7-LTS, mixed mode, sharing)
```

Do you have any idea ?

**Comment by gdelataillade** [comment]
Hi @tattuu 

Thank you so much for sharing your work, I'm adding it to the plugin !

**Comment by tattuu** [comment]
I'm glad that the merge went smoothly!

I am happy to have been able to contribute to you and this project!

I wish for the development of both you and the project.

**Comment by gdelataillade** [comment]
Thank you ! You're officially a contributor of the plugin now, congratulations !

**Pull request merged**
