### PR TITLE
Feature -> Add iOS Background Fetch

### LINKED ISSUE #78: Alarm not ringing anymore after 6+ hours
Version: 1.2.1

### PR DESCRIPTION
**Pull request by gdelataillade**
Play silent audio until alarm rings in order to keep app active.
Check every 30 minutes if app is still active.

### CODE REVIEW

**Comment by dev-chetan** [comment]
@gdelataillade Hello, please check  android is not working.

Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - file:/Users/dev-chetan/Documents/mindset/mindset-app-flutter/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :background_fetch

**Comment by gdelataillade** [comment]
Hi @dev-chetan 

Thanks for your message. I will take a look at it as soon as possible.

**Comment by gdelataillade** [comment]
Hi @dev-chetan

The issue was that I added the package `background_fetch` in the project for iOS, but it needed some Android installation steps. `background_fetch` is not used for Android in this project, only iOS, so I decided to code the Background Fetch feature directly in the native code and remove `background_fetch` dependency. This should fix your issue.

**Comment by gdelataillade** [comment]
Note that I updated iOS installation steps, take a look at the README.

**Comment by dev-chetan** [comment]
@gdelataillade Hello,
The alarm not ringing anymore after 6+ hours
Is this issue fixed?

**Comment by gdelataillade** [comment]
Hi @dev-chetan !

I'm working hard on fixing this issue in this pull request. I think I'm getting close to a working solution.

If you want to help, you can try the latest versions and let me know if it worked for you. Just use this package version:
`alarm: ^2.0.0-dev.5`

**Pull request merged**
