### PR TITLE
Feature -> Add notification action buttons (stop)

### PR DESCRIPTION
**Pull request by gdelataillade**
Tasks:
- [x] Implement iOS stop
- [x] Implement Android stop
- [x] Tests on iOS
- [x] Tests on Android <12
- [x] Tests on Android 12+
- [x] Review & clean code
- [x] Add documentation
- [x] Update README

_Note: Snooze will not work on iOS if app was killed._

TODO: Notify contributors when version 4 is published.

### CODE REVIEW

**Comment by nafiskabbo** [comment]
When it will be published?

**Comment by gdelataillade** [comment]
> I need this feature because currently custom sounds cannot be stopped. When will it be pushed?

@nafiskabbo Give me a couple of weeks. I'm about to finish it but then I'll need to do a lot of testing.
If you are willing to help me test it will faster.

**Review by gdelataillade — COMMENTED** [review]
OK

**Comment by Nulinz** [comment]
how to use 4.0.0-dev.1 or view the code of 4.0.0-dev.1 ??  when it should be released

**Comment by gdelataillade** [comment]
Hi @Nulinz 

To use this PR just set version `4.0.0-dev.2` in your pubspec. Stable version should be released very soon when I finish fixing some minor issues. Let me know if you find any.

**Pull request merged**
